spring:
  application:
    name: user-task

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/user_task}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}

    hikari:
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:25}
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 43200000

  flyway:
    user: ${FLYWAY_USER:postgres}
    password: ${FLYWAY_PASSWORD:postgres}
    locations: db/migration
    installed-by: ${spring.application.name}
    enabled: true

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        ddl-auto: none

logging:
  level:
    org.springframework.ws.client: TRACE
    org.springframework.ws.server: TRACE