spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/students}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}

  flyway:
    user: ${FLYWAY_USER:postgres}
    password: ${FLYWAY_PASSWORD:postgres}
    locations: db/migration
    installed-by: ${spring.application.name}
    enabled: true